name: Python script

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          gcp_project: 'terra-incognita-cote-ivoire'
          credentials: ${{ secrets.DEPLOY_VIEWS }}

      - name: Create a table
        run: |
          python plugin_scripts/create_tables.py